export const postActionTypes = {
  GET_POSTS: "GET_POSTS",
  GET_IMAGE: "GET_IMAGE",
  POST_ERROR: "POST_ERROR",
  UPDATE_LIKES: "UPDATE_LIKES",
  DELETE_POST: "DELETE_POST",
  ADD_COMMENT: "ADD_COMMENT",
  REMOVE_COMMENT: "REMOVE_COMMENT"
};
